/// Flutter icons MyAppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyAppIcons
///      fonts:
///       - asset: fonts/MyAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyAppIcons {
  MyAppIcons._();

  static const _kFontFam = 'MyAppIcons';
  static const String _kFontPkg = null;

  static const IconData glucose = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medicine = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exercise = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
